### ISSUE TITLE
Mapping to X86

### ISSUE THREAD

**Issue by wangchenguang123** [jiegec/unofficial-loongarch-intrinsics-guide#1]
Hello author, I came across your open-source repository while studying LoongArch vector functions. May I ask if this direction may have a mapping relationship with the SSE of X86？

**Comment by wangchenguang123** [comment]
and where i can find all LoongArch intrinsics functions explain,
hope for your reply

**Comment by jiegec** [comment]
> Hello author, I came across your open-source repository while studying LoongArch vector functions. May I ask if this direction may have a mapping relationship with the SSE of X86？

I have plans to do it actually, and we can learn it from the SIMDe source code.

**Comment by jiegec** [comment]
> and where i can find all LoongArch intrinsics functions explain, hope for your reply

The explanation and C source code are written by myself (learning from QEMU & GCC and by doing experiments on real machines).

**Comment by jiegec** [comment]
I have a WIP version at http://jia.je/unofficial-loongarch-intrinsics-guide/migrating_sse/. If you are interested, you are welcome to contribute.

**Comment by wangchenguang123** [comment]
> I have a WIP version at http://jia.je/unofficial-loongarch-intrinsics-guide/migrating_sse/. If you are interested, you are welcome to contribute.

非常感谢老师的回复，我正在从numpy opencv等库中尝试寻找其中的映射关系

**Comment by wangchenguang123** [comment]
在如下图这些函数中是SSE中创建寄存器并逆序赋值的几个函数
![图片](https://github.com/jiegec/unofficial-loongarch-intrinsics-guide/assets/56055887/3157e1b5-f38d-4bd3-93c5-b8a158c4242d)
在numpy的lsx实现中举一个例子(_mm_setr_pd) 如下图所示 采用直接赋值 而不使用内置函数的形式 这该如何确定对应关系
LoongArch-LSX：
![图片](https://github.com/jiegec/unofficial-loongarch-intrinsics-guide/assets/56055887/98fb803b-37ae-47a3-86a1-21b4eeca79a1)
![图片](https://github.com/jiegec/unofficial-loongarch-intrinsics-guide/assets/56055887/96c352f6-4907-47d7-a053-e340629b1ddd)
X86-SSE：
![图片](https://github.com/jiegec/unofficial-loongarch-intrinsics-guide/assets/56055887/c4682578-6327-4fa4-9a37-a4b3c581c96f)

**Comment by jiegec** [comment]
用英文标注一下，直接用 C 语法构造吧，让编译器去优化。
