### ISSUE TITLE
__lsx_vbitseli_b Description文档错误

### ISSUE THREAD

**Issue by SurfaceMan** [jiegec/unofficial-loongarch-intrinsics-guide#10]
__m128i __lsx_vbitseli_b (__m128i a, __m128i b, imm0_255 imm)
Description
Compute bitwise selection: for each bit position, if the bit in a equals to one, copy the bit from imm to dst, otherwise copy from b.
应该是：
 if the bit in imm(不是a) equals to one, copy the bit from a(不是imm) to dst, otherwise copy from b.

**Comment by jiegec** [comment]
> __m128i __lsx_vbitseli_b (__m128i a, __m128i b, imm0_255 imm) Description Compute bitwise selection: for each bit position, if the bit in a equals to one, copy the bit from imm to dst, otherwise copy from b. 应该是： if the bit in imm(不是a) equals to one, copy the bit from a(不是imm) to dst, otherwise copy from b.

根据我在真机上的观察，前面的描述是正确的：dst.byte[i] = (~a.byte[i] & b.byte[i]) | (a.byte[i] & (u8)imm);

**Comment by SurfaceMan** [comment]
> > __m128i __lsx_vbitseli_b (__m128i a, __m128i b, imm0_255 imm) Description Compute bitwise selection: for each bit position, if the bit in a equals to one, copy the bit from imm to dst, otherwise copy from b. 应该是： if the bit in imm(不是a) equals to one, copy the bit from a(不是imm) to dst, otherwise copy from b.
> 
> 根据我在真机上的观察，前面的描述是正确的：dst.byte[i] = (~a.byte[i] & b.byte[i]) | (a.byte[i] & (u8)imm);

我试了一下，确实如此，a应该理解为mask。

还有一个其他的问题，__lsx_vld加载数据的时候不需要考虑内存地址对齐吗？
如下代码是可以正常运行的：
std::vector<uint8_t> data{0, 1, 2,  3,  4,  5,  6,  7,
                            8, 9, 10, 11, 12, 13, 14, 15};
  std::vector<uint8_t> data2(16, 2);
  std::vector<uint8_t> out(16, 0);
  auto vec = __lsx_vld(data.data(), 0);
  auto vec2 = __lsx_vld(data2.data(), 0);
  auto vec3 = __lsx_vadd_b(vec, vec2);
  __lsx_vstx(vec3, out.data(), 0);
就是data、data2、out分配的时候完全没考虑对齐，还是说__lsx_vld支持非对齐加载？

**Comment by jiegec** [comment]
> > > __m128i __lsx_vbitseli_b (__m128i a, __m128i b, imm0_255 imm) Description Compute bitwise selection: for each bit position, if the bit in a equals to one, copy the bit from imm to dst, otherwise copy from b. 应该是： if the bit in imm(不是a) equals to one, copy the bit from a(不是imm) to dst, otherwise copy from b.
> > 
> > 
> > 根据我在真机上的观察，前面的描述是正确的：dst.byte[i] = (~a.byte[i] & b.byte[i]) | (a.byte[i] & (u8)imm);
> 
> 我试了一下，确实如此，a应该理解为mask。
> 
> 还有一个其他的问题，__lsx_vld加载数据的时候不需要考虑内存地址对齐吗？ 如下代码是可以正常运行的： std::vector<uint8_t> data{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}; std::vector<uint8_t> data2(16, 2); std::vector<uint8_t> out(16, 0); auto vec = __lsx_vld(data.data(), 0); auto vec2 = __lsx_vld(data2.data(), 0); auto vec3 = __lsx_vadd_b(vec, vec2); __lsx_vstx(vec3, out.data(), 0); 就是data、data2、out分配的时候完全没考虑对齐，还是说__lsx_vld支持非对齐加载？

你可以测试一下，硬件是否支持非对齐的 vld 指令，如果支持的话，可能会有性能损失；如果不支持的话，看看是什么行为。

**Comment by SurfaceMan** [comment]
用__lsx_vld可以加载，但是__lsx_vldrepl_b不行
