### ISSUE TITLE
为什么您手册中的某些指令在 GCC Intrinsics 头文件中找不到声明？

### ISSUE THREAD

**Issue by 163jh** [jiegec/unofficial-loongarch-intrinsics-guide#13]
您手册中的很多 Intrinsics 在 github 的官方 GCC 镜像中的 <lsxintrin.h> 和 <lasxintrin.h> 找不到声明，这是为什么呢？
比如 __lasx_xvshuf4i_w，__lsx_vsat_hu 和 __lsx_vsubi_hu等。
[https://github.com/gcc-mirror/gcc/blob/master/gcc/config/loongarch/lsxintrin.h](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/loongarch/lsxintrin.h)
[https://github.com/gcc-mirror/gcc/blob/master/gcc/config/loongarch/lasxintrin.h](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/loongarch/lasxintrin.h)

**Comment by jiegec** [comment]
你说的这三个intrinsic就在这两个文件里呢，全文搜索就能找到。

**Comment by 163jh** [comment]
好的，谢谢您。
