### ISSUE TITLE
LSX 和 LASX 如何精细操作向量寄存器中的某一部分？

### ISSUE THREAD

**Issue by 163jh** [jiegec/unofficial-loongarch-intrinsics-guide#15]
类似 ARM NEON Intrinsics 里 vzip1q_u8(uint8x16_t a, uint8x16_t b) 和 vzip1_u8(uint8x8_t a, uint8x8_t b) 的区别。前者操作 NEON 寄存器的整个128位，返回的也是128位的结果，后者则只操作两个寄存器的低64位，返回值也只影响低64位的结果。
甚至包括 uint16x8_t vsubl_u8(uint8x8_t a, uint8x8_t b) 这种参数是两个64位，而返回值却是128位的结果，使用 LSX 要如何实现同样的功能呢？

**Comment by jiegec** [comment]
建议你通读一遍所有的lsx intrinsic，再研究如何实现精细操作。

**Comment by 163jh** [comment]
好的，谢谢您。
