### ISSUE TITLE
能否详细解释一下__lsx_vmsknz_b？

### ISSUE THREAD

**Issue by 163jh** [jiegec/unofficial-loongarch-intrinsics-guide#5]
For each 8-bit element in a, if the element is non-zero, set one bit in dst, otherwise clear it.
这句话的意思我没理解透彻，是每8位里任意一位不为0在位图里就置1,还是看最高有效位为1就置1？

**Comment by jiegec** [comment]
任意一位不为零，因为这里说的是 8-bit element 是否等于 0。如果只看最高位，实际上就是看符号，那应该是 vmskgez 了。

不过你也提醒我了，代码里应该添加一些例子，方便理解。

**Comment by 163jh** [comment]
好的，谢谢您。

**Comment by jiegec** [comment]
我往文档添加了例子，如果你有兴趣的话，也可以贡献（见 code/examples.cpp）
