### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zp-art** [jiegec/unofficial-loongarch-intrinsics-guide#6]
__m128i __lsx_vldrepl_w (void *, imm_n512_511);函数里面，第二参数 imm_n512_511, an integer literal in range -512 to 511什么意思呢？怎么用啊，这应该是加载一个数组进去，第二个参数感觉没作用啊

**Comment by jiegec** [comment]
> __m128i __lsx_vldrepl_w (void *, imm_n512_511);函数里面，第二参数 imm_n512_511, an integer literal in range -512 to 511什么意思呢？怎么用啊，这应该是加载一个数组进去，第二个参数感觉没作用啊

第二个参数是地址偏移。第一个参数是基地址，第二个参数是偏移（移位前），实际访存的地址是第一个参数+第二个参数（移位后）。

其实我觉得地址偏移这个参数可以不暴露在 intrinsic 上，而是让编译器去优化：如果第一个参数涉及到地址计算，可以把地址计算中的立即数放到 vldrepl 指令里。

建议阅读：[__m128i __lsx_vldrepl_b (void * addr, imm_n2048_2047 offset)](https://jia.je/unofficial-loongarch-intrinsics-guide/lsx/memory/#__m128i-__lsx_vldrepl_b-void-addr-imm_n2048_2047-offset)。

**Comment by zp-art** [comment]
如果我想实现a和b向量的相加，__lsx_vldrepl_w函数第二个参数应该如何设置？#include<lsxintrin.h>
#include<stdio.h>

int main() {
    int a[4] = {1, 2, 3 ,4};
    int b[4] = {5, 6 ,7, 8};
    __m128i v1 = __lsx_vldrepl_w(a,  4);
    __m128i v2 = __lsx_vldrepl_w(b, 4);
    __m128i v3 = __lsx_vadda_w(v1, v2);
    for(int i = 0; i < 4; i++) {

        printf("%d\n", v3[i]);
    }
    return 0;
}

**Comment by jiegec** [comment]
你想要加载整个 a 数组，应该用 vld，而不是 vldrepl：vldrepl 是加载一个元素，然后复制到所有元素。另外，偏移设成 0 就可以了。

**Comment by zp-art** [comment]
好的，我明白了，谢谢您
