### ISSUE TITLE
你好，我想问下是否只能加载整数数组进去嘛？我看返回值都是以i结尾的

### ISSUE THREAD

**Issue by zp-art** [jiegec/unofficial-loongarch-intrinsics-guide#7]

**Comment by jiegec** [comment]
__m128i 表示一个 128 位宽的 LSX 寄存器，里面可以放不同宽度的整数元素，例如你可以在里面放 16 个 8 位整数，或者 8 个 16 位整数，或者 4 个 32 位整数，或者 2 个 64 位整数。我建议你在网上找一些 x86 的 SIMD 教程，然后再移植到 LSX/LASX 上。

**Comment by zp-art** [comment]
x86的SIMD已经做完了，我是做VSIPL信号处理函数库的移植，在x86平台下已经完成了SIMD运算，我的意思是可以加载浮点类型数组进去嘛？信号处理很少有整数类型的




张鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiegec/unofficial-loongarch-intrinsics-guide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiegec/unofficial-loongarch-intrinsics-guide] 你好，我想问下是否只能加载整数数组进去嘛？我看返回值都是以i结尾的 (Issue #7)





 
Closed #7 as completed.

**Comment by jiegec** [comment]
浮点对应的类型是 __m128 和 __m128d。对于加载来说，整数和浮点是没有区别的，你 load 进来再进行格式转换即可。

**Comment by zp-art** [comment]
好的，我刚想明白了，感谢




张鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiegec/unofficial-loongarch-intrinsics-guide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiegec/unofficial-loongarch-intrinsics-guide] 你好，我想问下是否只能加载整数数组进去嘛？我看返回值都是以i结尾的 (Issue #7)





 
浮点对应的类型是 __m128 和 __m128d。对于加载来说，整数和浮点是没有区别的，你 load 进来再进行格式转换即可。

**Comment by jiegec** [comment]
一个例子：https://godbolt.org/z/rnd9evoYh

**Comment by zp-art** [comment]
好的，今天麻烦您了，太感谢了，祝您新的一年身体健康，工作顺利。




张鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiegec/unofficial-loongarch-intrinsics-guide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiegec/unofficial-loongarch-intrinsics-guide] 你好，我想问下是否只能加载整数数组进去嘛？我看返回值都是以i结尾的 (Issue #7)





 
一个例子：https://godbolt.org/z/rnd9evoYh
